#ifndef OM_LOG_H
#define OM_LOG_H

#define OPENBITTUBE_LOG_CATEGORY "OM"

#define OMINFO  CLOG(INFO, OPENBITTUBE_LOG_CATEGORY)
#define OMWARN  CLOG(WARNING, OPENBITTUBE_LOG_CATEGORY)
#define OMERROR CLOG(ERROR, OPENBITTUBE_LOG_CATEGORY)

#define OMVLOG1  CVLOG(1, OPENBITTUBE_LOG_CATEGORY)
#define OMVLOG2  CVLOG(2, OPENBITTUBE_LOG_CATEGORY)
#define OMVLOG3  CVLOG(3, OPENBITTUBE_LOG_CATEGORY)
#define OMVLOG4  CVLOG(4, OPENBITTUBE_LOG_CATEGORY)

#define OMINFO_IF(cond)  CLOG_IF(cond, INFO, OPENBITTUBE_LOG_CATEGORY)
#define OMWARN_IF(cond)  CLOG_IF(cond, WARNING, OPENBITTUBE_LOG_CATEGORY)
#define OMERROR_IF(cond) CLOG_IF(cond, ERROR, OPENBITTUBE_LOG_CATEGORY)


#endif // OM_LOG_H  
